
CREATE TABLE PACKAGE (
  PACKAGE_ID NUMERIC PRIMARY KEY,
  PACKAGE_NAME VARCHAR (40) NOT NULL,
  CALL_RATE NUMERIC NOT NULL,
  SMS_RATE NUMERIC NOT NULL,
  DATA_RATE NUMERIC NOT NULL,
  FNF_LIMIT NUMERIC NOT NULL
);

CREATE TABLE VOUCHERS(
  VOUCHER_ID NUMERIC PRIMARY KEY,
  CODE NUMERIC NOT NULL,
  VALIDITY NUMERIC NOT NULL,
  DESCRIPTION VARCHAR (200) NOT NULL
);

CREATE TABLE OFFERS (
  OFFER_ID NUMERIC PRIMARY KEY
);

CREATE TABLE REWARD_OFFER (
  OFFER_ID NUMERIC PRIMARY KEY,
  PRICE NUMERIC,
  VALIDITY NUMERIC NOT NULL,
  REWARD_POINTS NUMERIC,
  POINTS_NEED NUMERIC NOT NULL,
  MB_AMOUNT NUMERIC NOT NULL
);

CREATE TABLE SMS_OFFER
(
  OFFER_ID NUMERIC PRIMARY KEY,
  PRICE NUMERIC,
  VALIDITY NUMERIC NOT NULL,
  REWARD_POINTS NUMERIC,
	SMS_AMOUNT NUMERIC NOT NULL
);

CREATE TABLE INTERNET_OFFER(
  OFFER_ID NUMERIC PRIMARY KEY,
  PRICE NUMERIC,
  VALIDITY NUMERIC NOT NULL,
  REWARD_POINTS NUMERIC,
  DATA_AMOUNT NUMERIC NOT NULL
);

CREATE TABLE TALK_TIME_OFFER(
  OFFER_ID NUMERIC PRIMARY KEY,
  PRICE NUMERIC,
  VALIDITY NUMERIC NOT NULL,
  REWARD_POINTS NUMERIC,
  TALK_TIME NUMERIC NOT NULL
);

CREATE TABLE GENERAL_OFFER (
  OFFER_ID NUMERIC PRIMARY KEY,
  PRICE NUMERIC,
  VALIDITY NUMERIC NOT NULL,
  CUSTOM_ID SERIAL,
  MUNITE NUMERIC,
  MB_AMOUNT NUMERIC,
  SMS_AMOUNT NUMERIC
);

CREATE TABLE STAR (
  STAR_ID NUMERIC PRIMARY KEY,
  TYPE VARCHAR (20) NOT NULL,
  AVERAGE_USES NUMERIC NOT NULL,
  VALIDITY NUMERIC NOT NULL
);

CREATE TABLE STARS_OFFER (
  OFFER_ID NUMERIC PRIMARY KEY,
  OFFER_NAME VARCHAR(40) NOT NULL,
  TITLE VARCHAR (40) NOT NULL,
  DESCRIPTION VARCHAR (200),
  STAR_ID NUMERIC NOT NULL,
  CONSTRAINT STAR_FK FOREIGN KEY (STAR_ID)
    REFERENCES STAR (STAR_ID)
    ON DELETE CASCADE
);

CREATE TABLE USERS (
  MOBILE_NUMBER NUMERIC PRIMARY KEY,
  BALANCE NUMERIC NOT NULL,
  TOTAL_MB NUMERIC,
  TOTAL_REWARD_POINT NUMERIC,
  EMERGENCY_BALANCE_DUE NUMERIC,
  USER_NAME VARCHAR(40) NOT NULL,
  TOTAL_TALK_TIME NUMERIC,
  TOTAL_OFFER_SMS NUMERIC,
  PACKAGE_ID NUMERIC NOT NULL,
  STAR_ID NUMERIC,
  STAR_DATE TIMESTAMPTZ,
  CONSTRAINT PACKAGE_FK FOREIGN KEY (PACKAGE_ID)
    REFERENCES PACKAGE (PACKAGE_ID)
    ON DELETE CASCADE,
  CONSTRAINT STAR_FK FOREIGN KEY (STAR_ID)
    REFERENCES STAR (STAR_ID)
    ON DELETE CASCADE
);


CREATE TABLE USER_VOUCHER (
  USER_ID NUMERIC NOT NULL,
  VOUCHER_ID NUMERIC NOT NULL,
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (MOBILE_NUMBER)
    ON DELETE CASCADE,
  CONSTRAINT VOUCHER_FK FOREIGN KEY (VOUCHER_ID)
    REFERENCES VOUCHERS (VOUCHER_ID)
    ON DELETE CASCADE
);

CREATE TABLE LINK (
  LINKED_BY NUMERIC NOT NULL,
  LINKED_TO NUMERIC NOT NULL,
  PRIMARY KEY(LINKED_BY, LINKED_TO),
  CONSTRAINT LINKED_BY_FK FOREIGN KEY (LINKED_BY)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE,
  CONSTRAINT LINKED_TO_FK FOREIGN KEY (LINKED_TO)
    REFERENCES USERS(MOBILE_NUMBER) ON DELETE CASCADE
);


CREATE TABLE FNF (
  FNF_BY NUMERIC NOT NULL,
  FNF_TO NUMERIC NOT NULL,
  PRIMARY KEY(FNF_BY, FNF_TO),
  CONSTRAINT FNF_BY_FK FOREIGN KEY (FNF_BY)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE,
  CONSTRAINT FNF_TO_FK FOREIGN KEY (FNF_TO)
    REFERENCES USERS(MOBILE_NUMBER) ON DELETE CASCADE
);

CREATE TABLE PURCHASE_OFFER(
  USER_ID NUMERIC NOT NULL,
  OFFER_ID NUMERIC NOT NULL,
  PURCHASE_DATE TIMESTAMPTZ NOT NULL,
  CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE,
  CONSTRAINT OFFER_ID_FK FOREIGN KEY (OFFER_ID)
    REFERENCES OFFERS(OFFER_ID) ON DELETE CASCADE
);


CREATE TABLE HISTORY(
  H_DATE TIMESTAMPTZ NOT NULL,
  USER_ID NUMERIC NOT NULL,
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE
);

CREATE TABLE RECHARGE_HISTORY(
  AMOUNT NUMERIC NOT NULL,
  VALIDITY NUMERIC NOT NULL
) INHERITS (HISTORY);

CREATE TABLE INTERNET_HISTORY(
  MB_USED NUMERIC NOT NULL
) INHERITS (HISTORY);

CREATE TABLE SMS_HISTORY(
  SMS_NUMBER NUMERIC NOT NULL,
  COST NUMERIC NOT NULL,
  TYPE VARCHAR (40) NOT NULL
) INHERITS (HISTORY);

CREATE TABLE CALL_HISTORY(
  CALL_NUMBER NUMERIC NOT NULL,
  COST NUMERIC NOT NULL,
  TYPE VARCHAR (40) NOT NULL
) INHERITS (HISTORY);

CREATE TABLE EMERGENCY_BALANCE(
  USER_ID NUMERIC PRIMARY KEY,
  AMOUNT NUMERIC NOT NULL,
  TAKEN_DATE TIMESTAMPTZ NOT NULL,
  VALIDITY NUMERIC NOT NULL,
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE
);

CREATE TABLE NOTIFICATIONS(
  USER_ID NUMERIC NOT NULL,
  MESSAGE VARCHAR (200) NOT NULL,
  CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (MOBILE_NUMBER) ON DELETE CASCADE
);

drop table purchase_offer;

drop table recharge_history;

drop table internet_history;

drop table sms_history;

drop table call_history;

drop table history;

drop table reward_offer;

drop table sms_offer;

drop table internet_offer;

drop table talk_time_offer;

drop table general_offer;


drop table offers;

drop table stars_offer;

drop table user_voucher;

drop table vouchers;

drop table link;

drop table fnf;


drop table emergency_balance;

drop table notifications;

drop table users;

drop table star;

drop table package;



SELECT * FROM PG_TIMEZONE_NAMES;

SET TIMEZONE = 'Asia/Dhaka';
DO $$
BEGIN
RAISE NOTICE 'THE current MONTH DATE AND TIME IS %',TO_CHAR((NOW()+ interval '1 day' * 30)-now(), 'YYYY-MM-DD HH12:MI:SS PM');
END;
  $$


